### ISSUE TITLE
compilation failed (twatch-lib)

### ISSUE THREAD

**Issue by flecoufle** [virtualabs/hackwatch#18]
Hello Damien

I have in the log
#idf.py build
Failed to resolve component 'twatch-lib'

how can I install the lib ?

thanks

**Comment by totoff974** [comment]
try with submodule :

git clone --recurse-submodules https://github.com/virtualabs/hackwatch.git

**Comment by flecoufle** [comment]
perfect! thanks
I have done this one because already cloned
#git submodule update --init --recursive

I have another issue I close this one and post the build log in a another issue
