### ISSUE TITLE
driver/gpio.h: No such file or directory

### ISSUE THREAD

**Issue by reinethernal** [virtualabs/hackwatch#22]
Hi!
I run idf.py build and get such error

```
hackwatch/components/twatch-lib/drivers/i2c.c:3:10: fatal error: driver/gpio.h: No such file or directory
    3 | #include "driver/gpio.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
[2/71] Performing build step for 'bootloader'
[1/1] cd /home/reinethernal/firmware/hackw2/hackwatch/build/bootloader/esp-idf/esptool_py && /home/reinethernal/.espressif/python_env/idf5.0_py3.10_env/bin/python /home/reinethernal/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 /home/reinethernal/firmware/hackw2/hackwatch/build/bootloader/bootloader.bin
Bootloader binary size 0x6610 bytes. 0x9f0 bytes (9%) free.
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
root@re:/home/reinethernal/firmware/hackw2/hackwatch#

```

**Comment by dbarzin** [comment]
I got the same issue with the current version :

esp/hackwatch/components/twatch-lib/inc/drivers/axp20x.h:47:10: fatal error: driver/gpio.h: No such file or directory
   47 | #include "driver/gpio.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.

**Comment by Nels885** [comment]
Hi, currently the compilation does not work with the latest version of ESP-IDF, you have to use the commit 01d014c42def8d0c19e1ce55c07de6761e092ffa .

**Comment by virtualabs** [comment]
It looks like I made a bad choice to move from ESP-IDF version 4.4.2 to 5.0-dev, so I rolled back the code to version 4.4.2 in order to fix everything. Code should compile fine and without errors/warning with ESP-IDF 4.4.2 (latest stable).

**Comment by virtualabs** [comment]
Issue fixed, closing it.
