### ISSUE TITLE
Suggested optimization of the clock setting

### ISSUE THREAD

**Issue by Nels885** [virtualabs/hackwatch#3]
After my first tests, I find that it makes more sense to switch to the min value when we reach the max value and vice versa, this avoids sliding in the other direction.

What do you think about it ?

**Comment by virtualabs** [comment]
Well, my last design is not the best one as swiping up and down to set hours and minutes might trigger a tile change if the move is not right on the numbers. I was thinking about another implementation where the user has to tap the numbers to set the clock hours and minutes. It may be more annoying, but in the end it avoids changing screen on a bad move. Looping over the numbers in this scenario is definitely needed.

**Comment by virtualabs** [comment]
Fixed by your last (accepted) pull request #5.
