### ISSUE TITLE
Freeze when switching to wifi scanner

### ISSUE THREAD

**Issue by Nels885** [virtualabs/hackwatch#35]
Hi,

I noticed that the twatch freezes when you activate or deactivate the wifi scanner and one is forced to do a hard reset.
We can also see that the sliding between the scanner tile and the channels tile is not fluid.

The problem is random, it occurs more easily when quickly changing between WiFi tiles.

**Comment by virtualabs** [comment]
This bug should be fixed now, the scanning strategy has been changed to avoid freezing the whole UI.
