### ISSUE TITLE
bouton Deauth - identification du ssid

### ISSUE THREAD

**Issue by totoff974** [virtualabs/hackwatch#4]
Lors du lancement du deauth le bouton passe avec le label "stop", en laissant le deauth actif et si on revient sur la liste des ssid visible et qu'on sélectionne un autre ssid le bouton deauth reste sur "stop".
Si beaucoup de ssid actif (notamment pour les spots wifi avec le même ssid à plusieurs émetteurs différents adresses macs) il n'est pas possible d’identifier sur quel ssid le deauth est actif.

Peut-être envisager de mettre un fond ou une couleur différents,dans la liste des ssid, sur le ssid où le deauth est actif afin d'identifier ce dernier ?

**Comment by virtualabs** [comment]
J'ai ajouté dans la todo list le support de messages spécifiques permettant de gérer ce qu'il se passe quand on quitte un écran, de cette façon le deauth s'arrêtera dès que l'écran affichant le détail de l'AP est quitté. De même, le scanner WiFi pourra être activé seulement lorsque l'on affiche l'écran correspondant.

**Comment by virtualabs** [comment]
Normalement corrigé dans la dernière version, suite à l'implémentation du support des évènements de tiles.
