### ISSUE TITLE
UI3: Only physical button to escape "Deauth" screen

### ISSUE THREAD

**Issue by dglaude** [virtualabs/hackwatch#40]
In "Wifi Network", when selecting an SSID, you get into the only part of the UI that cannot be escaped without using the watch button.
For a user no knowing, that make the "Deauth" button the only option. :-)
For every other UI you can escape by swiping one direction or another, of for "Rogue AP" you can escape pressing the OK button.
Options:
* Offer a "Deauth" and a "Cancel" button so that there is an alternative way to get out.
* Make it possible to escape by swiping the screen (but then it is not modal like in "Rogue AP").

**Comment by virtualabs** [comment]
Both solutions look good, but since it is a modal the cancel button seems to be the best option without reworking the whole scanner. Maybe something to be improved for version after v2, certainly.

**Comment by virtualabs** [comment]
Deauth screen has been moved out of WiFi Scanner, and AP Info modal screen now does have its own "OK" button that make it disappear when clicked (changes introduced by commit cdbd7e92783524fdb1a6ca9fe5b260afc5dbdc5e).
