### ISSUE TITLE
UI4: Different user experience for "Deauth" and "Rogue AP".

### ISSUE THREAD

**Issue by dglaude** [virtualabs/hackwatch#41]
There is an inconsistency in the UI.

Both for "Rogue AP" and "Deauth" you want to select a wifi Network and do something on it (or like it).
For "Rogue AP" you have a button to select an SSID to mock, and then you can start or stop the "Rogue AP". The button to "Sel.AP" start a selection window with it's OK button.

For "Deauth" there is no dedicated menu, you are on the list of scanned network, and you can select one to do your attack. This is not consistent.

Options:
* Remove the "Deauth" option from the WiFi Network screen, and make a Deauth menu identical to the Rogue AP menu. That way it is identical experience and the WiFi Network screen is read only and not an attack screen (like the channel utilisation) and it is possible to compile the HackWatch without the attack feature.
* Remove the "Rogue AP" screen and make the selection of attack after the selection of "WiFi Network". So once a network is selected you would have the option to either do "Deauth" or "Rogue AP" or "Nothing"

Right now, I prefer the first option, with dedicated screen for "Deauth" and "Rogue AP", also because the "Deauth" and/or the "Rogue AP" could run in the background (?), just like "TV B Gone", so it is useful to have a dedicated screen for each (where the attack can be stopped).

**Comment by virtualabs** [comment]
Originally, the fact this Rogue AP tool is separated from the scanner was to allow modular firmware compilation (one may want a rogue AP feature without having the full scanner tool, even if it relies on the same WiFi scanning engine). 

I totally agree this Deauth feature must have its own screen (tile) that is similar to the Rogue AP one (same behavior as well), that makes more sense and the end user will be able to compile his/her firmware with or without this attack feature. 

Also, Deauth and Rogue AP features cannot run both in background as they rely on the same WiFi controller, but it may be possible to enable one or another and keep it running in background while allowing the use to navigate trough the UI. Deep sleep mode will then be disabled to keep the attack active, and will be enabled back once the attack is stopped by the user.

**Comment by Nels885** [comment]
I like the idea of the tile for the Deauth as for Rogue AP, I have free time this weekend so I will work on its integration.

**Comment by dglaude** [comment]
I am super happy you made the best of my 4 UI issue.
Some ideas where contradictory as I was going on in the thinking process.
"Deauth" like "Rogue AP" is the best option.

For the background mode, it just need to be clear if something stay in the background or not.
Like the TV-B Gone is Stealth and run while you have the watch face.
Maybe you want the same for Deauth or Rogue AP...
If one disable the other, you need a warning saying so.

**Comment by virtualabs** [comment]
Thanks top PR #42, Deauth has now its own screen and behaves exactly as the Rogue AP screen.
