### ISSUE TITLE
Refresh and aging of entry in WiFi Networks tile

### ISSUE THREAD

**Issue by dglaude** [virtualabs/hackwatch#44]
I have been using the watch in "war driving" mode: Keeping the Network tile open and driving near homes.

Pretty quickly the screen stop updating, no new network and visible network do not disappear even if very far away.

I am afraid that by testing in a stable/static location, some problems could go unnoticed. Maybe we need to add and remove SSID and check how/when the info is updated.

Not a big issue for my use case, going somewhere with the watch turned off and turning it on in the place where I want to use it.

**Comment by virtualabs** [comment]
I reworked the whole WiFi scanner, looked for any potential bug and found out and fixed two nasty bugs in commit 5b566067fc2c0e85fc06b881b3361704a75d7aac. Hope this helps, and thanks for the issue !
