### ISSUE TITLE
Please update the "About" to match v2 release.

### ISSUE THREAD

**Issue by dglaude** [virtualabs/hackwatch#45]
The current "About" say
```T-Watch 2020 v1/v2 compatible firmware providing WiFi and BLE testing tools (and also, a watch :D)```

It should be updated as to not exclude v3 watch.
Either do not specift v1/v2 or write v1/v2/v3.

Also it say Wifi and BLE, but does not talk about IR.

**Comment by virtualabs** [comment]
About section updated, thank you !
